# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# TODO: update dependabot to use conventional commits https://dev.to/kengotoda/a-complete-guide-to-use-dependabot-with-semantic-release-and-vercel-ncc-for-github-actions-230p

version: 2
updates:

  # Pipeline Service
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/PipelineService" # Location of package manifests
    target-branch: "dev"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/PipelineService"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  # Pipeline Service (Unit Tests)
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/PipelineService.UnitTests" # Location of package manifests
    target-branch: "dev"
    schedule:
      interval: "weekly"

  # File Service
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/FileService" # Location of package manifests
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/FileService"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  # Operation Worker
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/OperationWorker" # Location of package manifests
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/OperationWorker" # Location of package manifests
    target-branch: "dev"
    schedule:
      interval: "weekly"

  # Dataset Service
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/DataSetService" # Location of package manifests
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/DataSetService" # Location of package manifests
    target-branch: "dev"
    schedule:
      interval: "weekly"

  # Learning Service
  - package-ecosystem: "pip"
    directory: "/LearningService"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/LearningService"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  # Pipeline Simulation (MCTS)
  - package-ecosystem: "pip"
    directory: "/PipelineSimulationMcts"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/PipelineSimulationMcts"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  # Dev Frontend
  - package-ecosystem: "npm"
    directory: "/DevFrontend"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/DevFrontend"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  # Neo4j Plugins
  - package-ecosystem: "maven"
    directory: "/Neo4jPlugins"
    target-branch: "dev"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/Neo4jPlugins"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  # MySqlDatabase
  - package-ecosystem: "docker"
    directory: "/MySqlDatabase"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  # MLflow
  - package-ecosystem: "docker"
    directory: "/MLflowServer"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/MLflowServer"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  # Edge Server
  - package-ecosystem: "docker"
    directory: "/EdgeServer"
    target-branch: "dev"
    schedule:
      interval: "weekly"
