version: "3.8"
services:

  # Development Frontend
  dev-frontend:
    build:
      context: ./DevFrontend
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"

  # Pipeline Service
  pipeline-service:
    build:
      context: ./PipelineService
      dockerfile: ./Dockerfile
    environment:
      Logging__LogLevel__Default: Information
      ASPNETCORE_ENVIRONMENT: Development
      EVENT_BUS__MQTT_HOST: message-broker
      EVENT_BUS__MQTT_CLIENT_ID: pipeline-service-1
      EDGE_EVENT_BUS__MQTT_HOST: edge-message-broker
      EDGE_EVENT_BUS__MQTT_PORT: 1883
      EDGE_EVENT_BUS__MQTT_CLIENT_ID: pipeline-service-1
    ports:
      - "5000:80"
    depends_on:
      - message-broker

  # Node Worker 1
  node-worker:
    build:
      context: ./NodeWorker
      dockerfile: ./Dockerfile
    environment:
      - MQTT_HOST=message-broker
      - DATASET_HOST=dataset-service
      - DATASET_PORT=5000
    depends_on:
      - message-broker
      - localstack-s3

  # Dataset Store
  dataset-service:
    build:
      context: ./DataSetService
      dockerfile: ./Dockerfile
    ports:
      - "5002:5000"
    expose:
      - 5002
    environment:
      - S3_HOST=localstack-s3
      - S3_PORT=4566
    depends_on:
      - localstack-s3

  # Message Broker
  message-broker:
    image: eclipse-mosquitto
    networks:
      - default
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./volumes/event-bus/mosquitto/config:/mosquitto/config

  # Edge Message Broker
  edge-message-broker:
    image: eclipse-mosquitto
    networks:
      - default
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - ./volumes/edge-event-bus/mosquitto/config:/mosquitto/config

  # S3 Bucket
  localstack-s3:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-2
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:4200,http://localhost:8080
    ports:
      - "4566:4566"
      - "4571:4571"
    # volumes:
    #   - ./volumes/localstack-data:/tmp/localstack