version: '3'
services:

  # Pipeline Service
  pipeline-service:
    build:
      context: ./PipelineService
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MQTT_CLIENT_ID=pipeline-service-1
    ports:
      - "5000:80"
    depends_on:
      - message-broker

  block-worker:
    build:
      context: ./BlockWorker
      dockerfile: ./Dockerfile
    environment:
      - MQTT_HOST=message-broker
    depends_on:
      - message-broker


  # Message Broker
  message-broker:
    image: eclipse-mosquitto
    networks:
      - default
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
    
