version: '3'
services:

  # Development Frontend
  dev-frontend:
    build:
      context: ./DevFrontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:80

  # Pipeline Service
  pipeline-service:
    build:
      context: ./PipelineService
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MQTT_CLIENT_ID=pipeline-service-1
    ports:
      - 5000:80
    depends_on:
      - message-broker

  # Block Worker 1
  block-worker:
    build:
      context: ./BlockWorker
      dockerfile: ./Dockerfile
    environment:
      - MQTT_HOST=message-broker
      - DATASET_HOST=dataset-service
      - DATASET_PORT=5000
    depends_on:
      - message-broker

  # Dataset Store
  dataset-service:
    build:
      context: ./DataSetService
      dockerfile: ./Dockerfile
    ports:
      - 5002:5000
    expose:
      - 5002

  # Message Broker
  message-broker:
    image: eclipse-mosquitto
    networks:
      - default
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
    