@startuml
'https://plantuml.com/deployment-diagram

title "Architecture Overview"

'Definitions'

rectangle "Frontend" {
    component "Development Frontend" << Angular Frontend >> as development_frontend
}

rectangle "Edge Services" {
    component "Reverse Proxy" << NGINX >> as reverse_proxy
    component "Edge Message Broker" << MQTT Broker >> as message_broker_edge
}

rectangle "Event Bus" {
    component "Internal Message Broker" << MQTT Broker >> as message_broker_internal
}

rectangle "Service Layer" {
    component "Pipeline Service" << .NET REST API >> as pipeline_service
    collections  "Operation Worker" <<Python Worker>> as worker
    component #line.dashed "Suggestion Service" << Python REST API >> as suggestion_service
    component "File Service" << .NET REST API >> as file_service
    component "MLflow Server" << MLflow >> as mlflow_server
}

rectangle "Persistence Layer" {
    component "Dataset Store" << Python REST API >> as dataset_store
}

rectangle "Database Layer" {
    database "Graph Database" << Neo4j >> as graph_db
    node "S3 BLOB Store" << Localstack >> as blob_store
    database #line.dashed "Dataset Database" << MongoDB >> as dataset_db
    database "SQL Database" << MySQL >> as mysql_db
}

'Interaction'

development_frontend <--> reverse_proxy
development_frontend --> reverse_proxy

reverse_proxy --> pipeline_service
reverse_proxy --> suggestion_service
suggestion_service <--> message_broker_internal
reverse_proxy --> file_service
reverse_proxy <--> message_broker_edge
reverse_proxy --> mlflow_server

pipeline_service --> graph_db
dataset_store --> dataset_db
file_service --> blob_store
pipeline_service <--> message_broker_internal
message_broker_internal <--> worker
mlflow_server --> mysql_db
mlflow_server --> blob_store

worker --> dataset_store
worker --> blob_store

message_broker_edge <--> pipeline_service

'TODO: This connection should no longer exist'
reverse_proxy --> dataset_store
'TODO: Default files should be seeded from file service PH-213'
dataset_store --> blob_store
@enduml
