// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PipelineService.Models;

#nullable disable

namespace PipelineService.Migrations
{
    [DbContext(typeof(EfDatabaseContext))]
    [Migration("20220707134415_AddOperationCountToMetrics")]
    partial class AddOperationCountToMetrics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PipelineService.Models.Metrics.CandidateProcessingMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Aborted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ActionCount")
                        .HasColumnType("int");

                    b.Property<int>("BatchNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CandidateCreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Error")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ImportEndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ImportStartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ImportSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OperationCount")
                        .HasColumnType("int");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ProcessingEndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ProcessingStartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("TaskId")
                        .HasMaxLength(256)
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CandidateProcessingMetrics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
