using System;

namespace PipelineService.Models.Pipeline
{
    /// <summary>
    /// A <code>SimpleBlock</code> has one input dataset and one output dataset.
    /// The output dataset is generated by executing the operation on the input dataset.
    /// </summary>
    public record SimpleBlock : Block
    {
        /// <summary>
        /// The id of the input dataset.
        /// </summary>
        public Guid? InputDatasetId { get; set; }

        /// <summary>
        /// The producing hash of the input dataset. 
        /// </summary>
        public string InputDatasetHash { get; set; }
    }
}