using System;
using PipelineService.Helper;

namespace PipelineService.Models.Pipeline
{
    /// <summary>
    /// A <code>SimpleBlock</code> has one input dataset and one output dataset.
    /// The output dataset is generated by executing the operation on the input dataset.
    /// </summary>
    public record SimpleBlock : Block
    {
        /// <summary>
        /// The id of the input dataset.
        /// </summary>
        public Guid? InputDatasetId { get; set; }

        /// <summary>
        /// The producing hash of the input dataset. 
        /// </summary>
        public string InputDatasetHash { get; set; }

        /// <summary>
        /// The key (id) the dataset produced by this operation is stored as.
        /// </summary>
        /// <remarks>
        /// Typically sha256(InputDataSetId|InputDataSetHash|OperationName|OperationConfiguration).
        /// </remarks>
        public string ResultKey =>
            HashHelper.ComputeHash(InputDatasetId, InputDatasetHash, Operation, OperationConfiguration);

        public override string IncludeInHash =>
            InputDatasetId.HasValue ? InputDatasetId.Value.ToString() : InputDatasetHash;
    }
}