name: Build and Publish Dev Frontend
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preparation
        id: prep
        run: |
          TAGS="docker.pkg.github.com/${{ github.repository }}:${{ github.sha }}"
          if [[ $GITHUB_REF == ref/head/master ]]; then
            TAGS="$TAGS,docker.pkg.github.com/${{ github.repository }}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./DevFrontend
          push: true
          tags: ${{ steps.prep.outputs.tags }}
